apiVersion: v1
kind: Pod
metadata:
  name: flask-app-1
  labels:
    app: flask
spec:
  containers:
  - name: flask-container
    image: technoavengers/mypythonflask_07_07
  - name: httpd-container
    image: httpd